//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeControl.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employees
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string data_ad { get; set; }
        public string codigo { get; set; }
        public string cpf { get; set; }
        public string cargo { get; set; }
        public string filial { get; set; }
    }
}
